// mockData.ts
export const mockProducts = [
    {
      id: 1,
      name: 'Wireless Headphones',
      price: 99.99,
      category: 'Electronics',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 2,
      name: 'Running Shoes',
      price: 59.99,
      category: 'Fashion',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 3,
      name: 'Coffee Maker',
      price: 39.99,
      category: 'Home Appliances',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 4,
      name: 'Smartphone',
      price: 699.99,
      category: 'Electronics',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 5,
      name: 'Backpack',
      price: 29.99,
      category: 'Fashion',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 6,
      name: 'Wireless Headphones',
      price: 99.99,
      category: 'Electronics',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 7,
      name: 'Running Shoes',
      price: 59.99,
      category: 'Fashion',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 8,
      name: 'Coffee Maker',
      price: 39.99,
      category: 'Home Appliances',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 9,
      name: 'Smartphone',
      price: 699.99,
      category: 'Electronics',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 10,
      name: 'Backpack',
      price: 29.99,
      category: 'Fashion',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 11,
      name: 'Wireless Headphones',
      price: 99.99,
      category: 'Electronics',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 12,
      name: 'Running Shoes',
      price: 59.99,
      category: 'Fashion',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 13,
      name: 'Coffee Maker',
      price: 39.99,
      category: 'Home Appliances',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 14,
      name: 'Smartphone',
      price: 699.99,
      category: 'Electronics',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 15,
      name: 'Backpack',
      price: 29.99,
      category: 'Fashion',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 16,
      name: 'Wireless Headphones',
      price: 99.99,
      category: 'Electronics',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 17,
      name: 'Running Shoes',
      price: 59.99,
      category: 'Fashion',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 18,
      name: 'Coffee Maker',
      price: 39.99,
      category: 'Home Appliances',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 19,
      name: 'Smartphone',
      price: 699.99,
      category: 'Electronics',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 20,
      name: 'Backpack',
      price: 29.99,
      category: 'Fashion',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 21,
      name: 'Wireless Headphones',
      price: 99.99,
      category: 'Electronics',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 22,
      name: 'Running Shoes',
      price: 59.99,
      category: 'Fashion',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 23,
      name: 'Coffee Maker',
      price: 39.99,
      category: 'Home Appliances',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 24,
      name: 'Smartphone',
      price: 699.99,
      category: 'Electronics',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 25,
      name: 'Backpack',
      price: 29.99,
      category: 'Fashion',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 26,
      name: 'Wireless Headphones',
      price: 99.99,
      category: 'Electronics',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 27,
      name: 'Running Shoes',
      price: 59.99,
      category: 'Fashion',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 28,
      name: 'Coffee Maker',
      price: 39.99,
      category: 'Home Appliances',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 29,
      name: 'Smartphone',
      price: 699.99,
      category: 'Electronics',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 30,
      name: 'Backpack',
      price: 29.99,
      category: 'Fashion',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 31,
      name: 'Wireless Headphones',
      price: 99.99,
      category: 'Electronics',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 32,
      name: 'Running Shoes',
      price: 59.99,
      category: 'Fashion',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 33,
      name: 'Coffee Maker',
      price: 39.99,
      category: 'Home Appliances',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 34,
      name: 'Smartphone',
      price: 699.99,
      category: 'Electronics',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 35,
      name: 'Backpack',
      price: 29.99,
      category: 'Fashion',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 36,
      name: 'Wireless Headphones',
      price: 99.99,
      category: 'Electronics',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 37,
      name: 'Running Shoes',
      price: 59.99,
      category: 'Fashion',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 38,
      name: 'Coffee Maker',
      price: 39.99,
      category: 'Home Appliances',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 39,
      name: 'Smartphone',
      price: 699.99,
      category: 'Electronics',
      image: 'https://picsum.photos/id/1/200/300',
    },
    {
      id: 40,
      name: 'Backpack',
      price: 29.99,
      category: 'Fashion',
      image: 'https://picsum.photos/id/1/200/300',
    },
  ];
  